### PR TITLE
Check deepest function when type checking field arguments

### PR DESCRIPTION
**Pull request by codygustafson**
This was checking if the field-type was a valid argument for the top-most function. This changes it to check the deepest function.

### CODE REVIEW

**Comment by joshcom** [comment]
Changes look good, but is there a test you can write that exposes this bug?

**Comment by codygustafson** [comment]
Good call, I added that test and squashed this.

**Comment by wlmcewen** [comment]
Good deal. I saw the test in the API and assumed it wasn't exposed well in here.

**Comment by codygustafson** [comment]
I had assumed it wasn't exposed well in here. I should have actually checked!

**Pull request merged**
